/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as ApiNb10AssistantRouteImport } from './routes/api/nb10-assistant'
import { Route as ApiRunnerAssistantRouteImport } from './routes/api/runner-assistant'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ClassSlugRouteImport } from './routes/class.$slug'
import { Route as TaskMainIdeaRouteImport } from './routes/task.main-idea'
import { Route as TaskNewBeginnings10RouteImport } from './routes/task.new-beginnings-10'
import { Route as TaskRunnerTaskIdRouteImport } from './routes/task.runner.$taskId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNb10AssistantRoute = ApiNb10AssistantRouteImport.update({
  id: '/api/nb10-assistant',
  path: '/api/nb10-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunnerAssistantRoute = ApiRunnerAssistantRouteImport.update({
  id: '/api/runner-assistant',
  path: '/api/runner-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassSlugRoute = ClassSlugRouteImport.update({
  id: '/class/$slug',
  path: '/class/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskMainIdeaRoute = TaskMainIdeaRouteImport.update({
  id: '/task/main-idea',
  path: '/task/main-idea',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskNewBeginnings10Route = TaskNewBeginnings10RouteImport.update({
  id: '/task/new-beginnings-10',
  path: '/task/new-beginnings-10',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskRunnerTaskIdRoute = TaskRunnerTaskIdRouteImport.update({
  id: '/task/runner/$taskId',
  path: '/task/runner/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/practice': typeof PracticeRoute
  '/teacher': typeof TeacherRoute
  '/api/nb10-assistant': typeof ApiNb10AssistantRoute
  '/api/runner-assistant': typeof ApiRunnerAssistantRoute
  '/api/tts': typeof ApiTtsRoute
  '/class/$slug': typeof ClassSlugRoute
  '/task/main-idea': typeof TaskMainIdeaRoute
  '/task/new-beginnings-10': typeof TaskNewBeginnings10Route
  '/task/runner/$taskId': typeof TaskRunnerTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/practice': typeof PracticeRoute
  '/teacher': typeof TeacherRoute
  '/api/nb10-assistant': typeof ApiNb10AssistantRoute
  '/api/runner-assistant': typeof ApiRunnerAssistantRoute
  '/api/tts': typeof ApiTtsRoute
  '/class/$slug': typeof ClassSlugRoute
  '/task/main-idea': typeof TaskMainIdeaRoute
  '/task/new-beginnings-10': typeof TaskNewBeginnings10Route
  '/task/runner/$taskId': typeof TaskRunnerTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/practice': typeof PracticeRoute
  '/teacher': typeof TeacherRoute
  '/api/nb10-assistant': typeof ApiNb10AssistantRoute
  '/api/runner-assistant': typeof ApiRunnerAssistantRoute
  '/api/tts': typeof ApiTtsRoute
  '/class/$slug': typeof ClassSlugRoute
  '/task/main-idea': typeof TaskMainIdeaRoute
  '/task/new-beginnings-10': typeof TaskNewBeginnings10Route
  '/task/runner/$taskId': typeof TaskRunnerTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/practice'
    | '/teacher'
    | '/api/nb10-assistant'
    | '/api/runner-assistant'
    | '/api/tts'
    | '/class/$slug'
    | '/task/main-idea'
    | '/task/new-beginnings-10'
    | '/task/runner/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/practice'
    | '/teacher'
    | '/api/nb10-assistant'
    | '/api/runner-assistant'
    | '/api/tts'
    | '/class/$slug'
    | '/task/main-idea'
    | '/task/new-beginnings-10'
    | '/task/runner/$taskId'
  id:
    | '__root__'
    | '/'
    | '/practice'
    | '/teacher'
    | '/api/nb10-assistant'
    | '/api/runner-assistant'
    | '/api/tts'
    | '/class/$slug'
    | '/task/main-idea'
    | '/task/new-beginnings-10'
    | '/task/runner/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PracticeRoute: typeof PracticeRoute
  TeacherRoute: typeof TeacherRoute
  ApiNb10AssistantRoute: typeof ApiNb10AssistantRoute
  ApiRunnerAssistantRoute: typeof ApiRunnerAssistantRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ClassSlugRoute: typeof ClassSlugRoute
  TaskMainIdeaRoute: typeof TaskMainIdeaRoute
  TaskNewBeginnings10Route: typeof TaskNewBeginnings10Route
  TaskRunnerTaskIdRoute: typeof TaskRunnerTaskIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nb10-assistant': {
      id: '/api/nb10-assistant'
      path: '/api/nb10-assistant'
      fullPath: '/api/nb10-assistant'
      preLoaderRoute: typeof ApiNb10AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runner-assistant': {
      id: '/api/runner-assistant'
      path: '/api/runner-assistant'
      fullPath: '/api/runner-assistant'
      preLoaderRoute: typeof ApiRunnerAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class/$slug': {
      id: '/class/$slug'
      path: '/class/$slug'
      fullPath: '/class/$slug'
      preLoaderRoute: typeof ClassSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task/main-idea': {
      id: '/task/main-idea'
      path: '/task/main-idea'
      fullPath: '/task/main-idea'
      preLoaderRoute: typeof TaskMainIdeaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task/new-beginnings-10': {
      id: '/task/new-beginnings-10'
      path: '/task/new-beginnings-10'
      fullPath: '/task/new-beginnings-10'
      preLoaderRoute: typeof TaskNewBeginnings10RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task/runner/$taskId': {
      id: '/task/runner/$taskId'
      path: '/task/runner/$taskId'
      fullPath: '/task/runner/$taskId'
      preLoaderRoute: typeof TaskRunnerTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PracticeRoute: PracticeRoute,
  TeacherRoute: TeacherRoute,
  ApiNb10AssistantRoute: ApiNb10AssistantRoute,
  ApiRunnerAssistantRoute: ApiRunnerAssistantRoute,
  ApiTtsRoute: ApiTtsRoute,
  ClassSlugRoute: ClassSlugRoute,
  TaskMainIdeaRoute: TaskMainIdeaRoute,
  TaskNewBeginnings10Route: TaskNewBeginnings10Route,
  TaskRunnerTaskIdRoute: TaskRunnerTaskIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
